version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nexus-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b1kb6v2ntx19"
s3_prefix = "nexus-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
